# Generated by Django 4.2.17 on 2024-12-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_app', '0002_streamplatforms_watchlist_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatforms',
            name='about',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
