# Generated by Django 4.2.17 on 2024-12-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_app', '0003_alter_streamplatforms_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='IMDB_app.streamplatforms'),
            preserve_default=False,
        ),
    ]
