# Generated by Django 4.2.17 on 2024-12-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_app', '0006_review_reviw_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Reviw_user',
            new_name='Review_user',
        ),
    ]
