# Generated by Django 4.2.17 on 2024-12-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_app', '0008_rename_watchlist_review_movielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movielist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='IMDB_app.watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='IMDB_app.streamplatforms'),
        ),
    ]
