# Generated by Django 4.2.17 on 2024-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_app', '0009_alter_review_movielist_alter_watchlist_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_reviews',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
